name: CI

on:
  push:
    branches:
      - '*'
    tags:
      - '!v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - uses: nttld/setup-ndk@v1
        with:
          ndk-version: r21e
#        - runs: ndk-build NDK_PROJECT_PATH=. APP_BUILD_SCRIPT=./Android.mk NDK_APPLICATION_MK=./Application.mk

      - run: |
          echo ndk.dir=$ANDROID_NDK_HOME > local.properties
          echo ndk.dir=$ANDROID_NDK_HOME > libuvccamera/local.properties
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

      - name: Environment info
        run: |
          gradle --version

      - name: build
        run: |
          cd MicroCam
          gradle build
          #./gradlew assembleDebug --stacktrace
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

#      - uses: actions/upload-artifact@v2
#        with:
#          name: flycatcher-apk-${{github.run_number}}-${{github.sha}}
#          path: ./app/build/outputs/**/*.apk

      - name: slack notification
        uses: rtCamp/action-slack-notify@v2.0.2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: sleeping-sickness
          SLACK_TITLE: MicroCam app build completed

